/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author 202101342011
 */
public class Agenda extends javax.swing.JFrame {

    /**
     * Creates new form Agenda
     */
    public Agenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JTextFiledName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        JLabelTelefone = new javax.swing.JLabel();
        JTextTelefone = new javax.swing.JTextField();
        JLabelEmail = new javax.swing.JLabel();
        JTextEmail = new javax.swing.JTextField();
        JLabelData = new javax.swing.JLabel();
        JTextData = new javax.swing.JTextField();
        JLabelHora = new javax.swing.JLabel();
        JTextHora = new javax.swing.JTextField();
        JLabelPasseio = new javax.swing.JLabel();
        JComboBoxPasseio = new javax.swing.JComboBox<>();
        JLabelObs = new javax.swing.JLabel();
        JTextObs = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        JLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(1, 51, 112));
        jLabel2.setText("Realizar Agendamento ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(1, 51, 112));
        jLabel3.setText("Nome");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        JTextFiledName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextFiledNameActionPerformed(evt);
            }
        });
        getContentPane().add(JTextFiledName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 180, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(1, 51, 112));
        jLabel4.setText("CPF/CNPJ:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 180, -1));

        JLabelTelefone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JLabelTelefone.setForeground(new java.awt.Color(1, 51, 112));
        JLabelTelefone.setText("Telefone:");
        getContentPane().add(JLabelTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        JTextTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextTelefoneActionPerformed(evt);
            }
        });
        getContentPane().add(JTextTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 180, -1));

        JLabelEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JLabelEmail.setForeground(new java.awt.Color(1, 51, 112));
        JLabelEmail.setText("Email:");
        getContentPane().add(JLabelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        JTextEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextEmailActionPerformed(evt);
            }
        });
        getContentPane().add(JTextEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 180, -1));

        JLabelData.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JLabelData.setForeground(new java.awt.Color(1, 51, 112));
        JLabelData.setText("Data:");
        getContentPane().add(JLabelData, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, -1, -1));
        getContentPane().add(JTextData, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 180, -1));

        JLabelHora.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JLabelHora.setForeground(new java.awt.Color(1, 51, 112));
        JLabelHora.setText("Hora:");
        getContentPane().add(JLabelHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, -1, -1));

        JTextHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextHoraActionPerformed(evt);
            }
        });
        getContentPane().add(JTextHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 180, -1));

        JLabelPasseio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JLabelPasseio.setForeground(new java.awt.Color(1, 51, 112));
        JLabelPasseio.setText("Passeio:");
        getContentPane().add(JLabelPasseio, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, -1, -1));

        JComboBoxPasseio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Passeio Barco" }));
        getContentPane().add(JComboBoxPasseio, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 180, -1));

        JLabelObs.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JLabelObs.setForeground(new java.awt.Color(1, 51, 112));
        JLabelObs.setText("Observações:");
        getContentPane().add(JLabelObs, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, -1, -1));
        getContentPane().add(JTextObs, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 480, 110));

        jButton1.setBackground(new java.awt.Color(0, 255, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Agendar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, 120, 40));

        JLabelFundo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/agenda_background.jpg"))); // NOI18N
        getContentPane().add(JLabelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 559));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTextFiledNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextFiledNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextFiledNameActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void JTextTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextTelefoneActionPerformed

    private void JTextEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextEmailActionPerformed

    private void JTextHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextHoraActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JComboBoxPasseio;
    private javax.swing.JLabel JLabelData;
    private javax.swing.JLabel JLabelEmail;
    private javax.swing.JLabel JLabelFundo;
    private javax.swing.JLabel JLabelHora;
    private javax.swing.JLabel JLabelObs;
    private javax.swing.JLabel JLabelPasseio;
    private javax.swing.JLabel JLabelTelefone;
    private javax.swing.JTextField JTextData;
    private javax.swing.JTextField JTextEmail;
    private javax.swing.JTextField JTextFiledName;
    private javax.swing.JTextField JTextHora;
    private javax.swing.JTextField JTextObs;
    private javax.swing.JTextField JTextTelefone;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
