package View;

import DAO.Conexao;
import DAO.FuncionarioDAO;
import Model.Funcionario;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;


public class FuncionarioForm extends javax.swing.JFrame {

    /**
     * Creates new form FuncionarioForm
     */
    public FuncionarioForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLabelCadastro = new javax.swing.JLabel();
        JLabelId = new javax.swing.JLabel();
        JTextID = new javax.swing.JTextField();
        JLabelCpf = new javax.swing.JLabel();
        JTextCpf = new javax.swing.JTextField();
        JLabelAcesso = new javax.swing.JLabel();
        JTextAcesso = new javax.swing.JTextField();
        JLabelTelefone = new javax.swing.JLabel();
        JTextTelefone = new javax.swing.JTextField();
        JLabelNascimento = new javax.swing.JLabel();
        JTextNascimento = new javax.swing.JTextField();
        JLabelNome = new javax.swing.JLabel();
        JTextNome = new javax.swing.JTextField();
        JLabelEmail = new javax.swing.JLabel();
        JTextEmail = new javax.swing.JTextField();
        JLabelPassword = new javax.swing.JLabel();
        JPasswordField = new javax.swing.JPasswordField();
        JLabelEndereco = new javax.swing.JLabel();
        JTextEndereco = new javax.swing.JTextField();
        JButtonSalvar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLabelCadastro.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        JLabelCadastro.setForeground(new java.awt.Color(1, 51, 112));
        JLabelCadastro.setText("Cadastro do Funcionário");
        getContentPane().add(JLabelCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, -1, -1));

        JLabelId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JLabelId.setForeground(new java.awt.Color(1, 51, 112));
        JLabelId.setText("ID:");
        getContentPane().add(JLabelId, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        JTextID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextIDActionPerformed(evt);
            }
        });
        getContentPane().add(JTextID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 220, -1));

        JLabelCpf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JLabelCpf.setForeground(new java.awt.Color(1, 51, 112));
        JLabelCpf.setText("CPF:");
        getContentPane().add(JLabelCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        JTextCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextCpfActionPerformed(evt);
            }
        });
        getContentPane().add(JTextCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 220, -1));

        JLabelAcesso.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JLabelAcesso.setForeground(new java.awt.Color(1, 51, 112));
        JLabelAcesso.setText("Acesso:");
        getContentPane().add(JLabelAcesso, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        JTextAcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextAcessoActionPerformed(evt);
            }
        });
        getContentPane().add(JTextAcesso, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 220, -1));

        JLabelTelefone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JLabelTelefone.setForeground(new java.awt.Color(1, 51, 112));
        JLabelTelefone.setText("Telefone:");
        getContentPane().add(JLabelTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));
        getContentPane().add(JTextTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 220, -1));

        JLabelNascimento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JLabelNascimento.setForeground(new java.awt.Color(1, 51, 112));
        JLabelNascimento.setText("Data de Nascimento:");
        getContentPane().add(JLabelNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        JTextNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextNascimentoActionPerformed(evt);
            }
        });
        getContentPane().add(JTextNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 150, -1));

        JLabelNome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JLabelNome.setForeground(new java.awt.Color(1, 51, 112));
        JLabelNome.setText("Nome:");
        getContentPane().add(JLabelNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, -1, -1));
        getContentPane().add(JTextNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 180, -1));

        JLabelEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JLabelEmail.setForeground(new java.awt.Color(1, 51, 112));
        JLabelEmail.setText("Email:");
        getContentPane().add(JLabelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, -1, -1));
        getContentPane().add(JTextEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 180, -1));

        JLabelPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JLabelPassword.setForeground(new java.awt.Color(1, 51, 112));
        JLabelPassword.setText("Senha:");
        getContentPane().add(JLabelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, -1, -1));
        getContentPane().add(JPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 180, -1));

        JLabelEndereco.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JLabelEndereco.setForeground(new java.awt.Color(1, 51, 112));
        JLabelEndereco.setText("Endereço:");
        getContentPane().add(JLabelEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, -1, -1));
        getContentPane().add(JTextEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 180, -1));

        JButtonSalvar.setBackground(new java.awt.Color(0, 255, 102));
        JButtonSalvar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JButtonSalvar.setText("Salvar");
        JButtonSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(JButtonSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 130, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/form_background.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 741, 487));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTextIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextIDActionPerformed

    private void JTextCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextCpfActionPerformed

    private void JTextAcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextAcessoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextAcessoActionPerformed

    private void JTextNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextNascimentoActionPerformed

    private void JButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonSalvarActionPerformed
        Funcionario funcionario = new Funcionario("Joao", "teste5@mail.com", "Senha@1");
        
        try {
            Connection conexao = new Conexao().getConnection(); 
            FuncionarioDAO funcionarioDAO = new FuncionarioDAO(conexao);
            funcionarioDAO.insert(funcionario);
            
        } catch (SQLException ex){
            Logger.getLogger(FuncionarioForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JButtonSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FuncionarioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FuncionarioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FuncionarioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FuncionarioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FuncionarioForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonSalvar;
    private javax.swing.JButton JButtonVoltar;
    private javax.swing.JLabel JLabelAcesso;
    private javax.swing.JLabel JLabelCadastro;
    private javax.swing.JLabel JLabelCpf;
    private javax.swing.JLabel JLabelEmail;
    private javax.swing.JLabel JLabelEndereco;
    private javax.swing.JLabel JLabelId;
    private javax.swing.JLabel JLabelNascimento;
    private javax.swing.JLabel JLabelNome;
    private javax.swing.JLabel JLabelPassword;
    private javax.swing.JLabel JLabelTelefone;
    private javax.swing.JPasswordField JPasswordField;
    private javax.swing.JTextField JTextAcesso;
    private javax.swing.JTextField JTextCpf;
    private javax.swing.JTextField JTextEmail;
    private javax.swing.JTextField JTextEndereco;
    private javax.swing.JTextField JTextID;
    private javax.swing.JTextField JTextNascimento;
    private javax.swing.JTextField JTextNome;
    private javax.swing.JTextField JTextTelefone;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
